### ISSUE TITLE
Problem decoding opus back to PCM

### ISSUE THREAD

**Issue by bwmarrin** [layeh/gopus#3]
I've been using your package for encoding opus for a little bit and it works fantastic.  I really appreciate you having wrote it :)

I've recently started trying to use it to decode opus back into PCM and I'm running into problems where the result doesn't sound right (very very choppy/skippy sounding).

So I wrote a little test program and published it here : https://github.com/bwmarrin/oencdec

With this test, I'm doing 2 channel audio and it looks like the decoder output is half the size that it should be.  The program reads in 1920 int16 values, encodes to opus, then decodes to PCM and the output is only 960 int16 values.

Any change you know what I'm doing wrong or is there possibly a bug in gopus somewhere?

**Comment by bontibon** [comment]
It should be fixed now. Thanks for the bug report!

**Comment by bwmarrin** [comment]
Oh great! Awesome response time.  Also, this may be the wrong place.. But I used your paypal donation button a few months back.  Just curious if that worked :)
