### ISSUE TITLE
Unable to compile on Windows

### ISSUE THREAD

**Issue by IMcPwn** [layeh/gopus#5]
I am unable to compile gopus on Windows with Go 1.6.1
```sh
$ go version
go version go1.6.1 windows/amd64
```

Error:
```sh
$ go get github.com/layeh/gopus
# github.com/layeh/gopus
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```

**Comment by bontibon** [comment]
You are trying to compile for amd64 using a 32-bit C compiler. To fix this, you could either:

1. Install a 64-bit C compiler, or
2. Build 32-bit versions of your software:

        CGO_ENABLED=1 GOARCH=386 <go commands>

**Comment by IMcPwn** [comment]
Thank you. I tried your second solution and it was successful.
```sh
CGO_ENABLED=1 GOARCH=386 go get github.com/layeh/gopus
```
