### ISSUE TITLE
Build errors on FreeBSD

### ISSUE THREAD

**Issue by mheppner** [layeh/gopus#6]
I was trying to install [matthieugrieger/mumbledj](https://github.com/matthieugrieger/mumbledj) and ran into issues when it tried to install gopus, which is listed in it's dependencies. I installing opus-1.1.2, opus-tools-0.1.9, and go-1.6.2. The C compiler is Clang 3.4.1. I don't know enough about Go to figure out what it's failing on, but here are the last few lines:

```
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `logSum':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:212: undefined reference to `floorf'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `surround_analysis':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/opus_multistream_encoder.c:323: undefined reference to `log'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `FLOAT2INT16':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/celt/float_cast.h:136: undefined reference to `lrintf'
/tmp/go-build789578334/github.com/layeh/gopus/_obj/opus_nonshared.cgo2.o: In function `tansig_approx':
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/mlp.c:88: undefined reference to `floorf'
.vendor/src/github.com/layeh/gopus/opus-1.1.2/src/mlp.c:88: undefined reference to `floorf'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
goop: Command failed with exit status 2
*** Error code 2
```

The output of `pkg-config --cflags opus` gives `-I/usr/local/include/opus`, which should mean that the Opus header files can be found, correct? There is an `opus.h` in that folder. It seems a lot of the undefined references are to math functions like pow, floor, cos, log, etc. How would I know if the math library is being linked (usually done with a compiler flag of `-lm`)?

**Comment by bontibon** [comment]
Thanks for the bug report. See if the most recent change fixes the error:

```
go get -u github.com/layeh/gopus
```

**Comment by bontibon** [comment]
Additionally, you should notice the errors are coming from "opus_nonshared.go". This means that the opus libraries do not have to be installed, as they are included in the repository.

**Comment by mheppner** [comment]
Fantastic, thanks! The only output I saw was a warning: `cc: warning: argument unused during compilation: '-pthread'`.
