### ISSUE TITLE
Error to run

### ISSUE THREAD

**Issue by S1ROZHA** [layeh/gopus#7]
root@S1ROZHA:~ # go install BogdanBot/cmd/bot
work/src/BogdanBot/cmd/bot/bot.go:18:2: code in directory /root/work/src/github.com/layeh/gopus expects import "layeh.com/gopus"
root@S1ROZHA:~#

**Comment by bontibon** [comment]
The import path for the package had to move from `github.com/layeh/gopus` to  `layeh.com/gopus`. Simply change all of your project's import statements accordingly.
