### ISSUE TITLE
Compilation fails because config.h can't be found

### ISSUE THREAD

**Issue by LeoVerto** [layeh/gopus#8]
I'm working on a project using gumble and thus also gopus as a dependency but `go build` fails whenever I try to import gumble/opus:

```
$ go build                                        
# github.com/LeoVerto/gumble-pulseaudio/vendor/layeh.com/gopus
vendor/layeh.com/gopus/opus_nonshared.go:9:11: fatal error: opus-1.1.2/config.h: No such file or directory
 // #include "opus-1.1.2/config.h"
           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

That file definitely exists and my local clone of gopus is up to date.

I'm sorry if this is something trivial, I haven't worked with Go outside of hacking on some mumble related stuff.

**Comment by bontibon** [comment]
Can you build a non-vendored copy of gopus?  I.e. does the following command succeed:
```
go get -u layeh.com/gopus
```

**Comment by LeoVerto** [comment]
Thanks, building gopus directly and removing it from vendors gets rid of the error (although godeps for some reason doesn't create a new folder in vendors).

I'm now trying to run an exact copy of the guimble mumble-audio-player example and even though it says it's playing music, it definitely isn't.

Should I make a separate ticket on gumble for this?

**Comment by bontibon** [comment]
gumble only supports Opus, so if you're on a pre-1.2.4 version of Mumble, you won't hear anything.  You can make sure audio is being received by the server by right clicking the bot user and clicking properties(?): if the last activity should be 0s when audio is being received from the user.
